name: Laravel CI

on:
  push:
    branches:
      - git-hub-actions
  pull_request:
    branches:
      - git-hub-actions

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.4
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, mysqli, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction


        # Set up Node.js and npm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Cache Node.js dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Install npm dependencies
      - name: Install npm dependencies
        run: npm install

      # Build assets with Vite
      - name: Build assets
        run: npm run build

      - name: Set environment file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Generate Passport keys
        run: php artisan passport:keys

      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: password
        run: php artisan migrate

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: password
        run: vendor/bin/phpunit
