name: Laravel CI

on:
  push:
    branches:
      - patterns
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Docker Compose services
        run: docker-compose up -d

      # - name: Set environment file for CI inside gateway_service
      #   run: docker-compose exec gateway_service cp .env.ci.testing .env.testing

      # - name: Install Composer dependencies inside gateway_service
      #   run: docker-compose exec gateway_service composer install --prefer-dist --no-progress --no-interaction

      # - name: Install npm dependencies inside gateway_service
      #   run: docker-compose exec gateway_service npm install

      # - name: Build assets inside gateway_service
      #   run: docker-compose exec gateway_service npm run build

      # - name: Generate application key inside gateway_service
      #   run: docker-compose exec -T gateway_service php artisan key:generate

      # - name: Generate Passport keys inside gateway_service
      #   run: docker-compose exec -T gateway_service php artisan passport:keys

      # - name: Wait for Database
      #   run: |
      #     chmod +x docker/scripts/wait-for-db.sh
      #     docker-compose exec gateway_service ./docker/scripts/wait-for-db.sh

      # - name: Run migrations inside gateway_service
      #   run: docker-compose exec gateway_service php artisan migrate --force


      # - name: Run migrations for testing inside gateway_service
      #   run: docker-compose exec -T gateway_service php artisan migrate --env=testing --no-interaction

      - name: Run tests inside gateway_service
        run: docker-compose exec -T gateway_service vendor/bin/phpunit

      - name: Stop Docker Compose services
        run: docker-compose down --volumes --remove-orphans
