name: Laravel CI - Main

on:
  workflow_run:
    workflows: ["Laravel CI - Staging"]
    types:
      - completed

  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'README/**'

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'README.md'
      - 'README/**'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  main-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Docker Compose services
        run: docker-compose up --build --force-recreate -d

      - name: Check if gateway_service is running
        run: |
          docker ps | grep gateway_service || echo "gateway_service is not running"

      - name: Wait for gateway_service to finish configurations and restart apache
        run: |
          until docker-compose logs gateway_service | grep -q "Running passport:keys for testing..." && \
              docker-compose logs gateway_service | grep -q "Encryption keys generated successfully" && \
              docker-compose logs gateway_service | grep -q "Command line: 'apache2 -D FOREGROUND'"; do
            echo "Waiting for gateway_service to be fully ready..."
            sleep 5
          done

      - name: Install Composer dependencies
        run: |
          docker-compose exec -T  gateway_service composer install --optimize-autoloader

      - name: Run tests inside gateway_service
        run: docker-compose exec -T gateway_service vendor/bin/phpunit

      - name: Stop Docker Compose services
        run: docker-compose down --volumes --remove-orphans
