name: Laravel CI - Staging

on:
  push:
    branches:
      - staging

  pull_request:
    branches:
      - staging
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'README.md'
      - 'README/**'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  staging-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: staging

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Docker Compose services
        run: docker-compose up --build --force-recreate -d

      - name: Check if gateway_service is running
        run: |
          docker ps | grep gateway_service || echo "gateway_service is not running"

      - name: Wait for gateway_service to finish configurations and restart apache
        run: |
          until docker-compose logs gateway_service | grep -q "Running passport:keys for testing..." && \
              docker-compose logs gateway_service | grep -q "Encryption keys generated successfully" && \
              docker-compose logs gateway_service | grep -q "Command line: 'apache2 -D FOREGROUND'"; do
            echo "Waiting for gateway_service to be fully ready..."
            sleep 5
          done

      - name: Install Composer dependencies
        run: |
          docker-compose exec -T  gateway_service composer install --optimize-autoloader

      - name: Run tests inside gateway_service
        run: docker-compose exec -T gateway_service vendor/bin/phpunit

      - name: Stop Docker Compose services
        run: docker-compose down --volumes --remove-orphans

      - name: Configure GitHub Token for authentication
        run: git config --global url."https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/magerosco/gateways.git".insteadOf "https://github.com/magerosco/gateways.git"


      - name: Push to main if tests pass
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git fetch origin main

          git checkout main
          git merge --no-ff staging -m "Auto-merge from staging"
          git push origin main --no-verify
